### PR TITLE
Use built-in instrument checking machinery instead of custom assertions

### PR DESCRIPTION
**Pull request by kennyjwilli**
This library currently throws its own assertions when a functions args or ret does not pass the written spec. This PR switches to use the pre-built `clojure.spec.test.alpha/instrument` functionality. If [Orchestra](https://github.com/jeaye/orchestra) is on the classpath, the `:ret` will also be checked.

### CODE REVIEW

**Comment by kennyjwilli** [comment]
@Frozenlock Curious on your thoughts on this approach instead. This would be a breaking change but certainly seems a lot simpler and more general moving forward.

**Comment by Frozenlock** [comment]
It looks simpler, but also introduces other dependencies.
In addition, like you said, it's a breaking change.

If I have to use `Orchestra` to check `:ret`, what's the point of this library? (ie why wouldn't I just use `Orchestra`?)

**Comment by kennyjwilli** [comment]
No extra deps are necessary unless you want to check :ret. Orchestra is a very small library that has no deps itself. I don't think there's much friction to asking people to add it for :ret checks. 

> If I have to use Orchestra to check :ret, what's the point of this library? (ie why wouldn't I just use Orchestra?)

See note [here](https://github.com/Provisdom/defn-spec#why-not-fdef)

**Comment by Frozenlock** [comment]
> No extra deps are necessary unless you want to check :ret. 

Sure, but I do check `:ret`. :confused: 

I don't understand why all those breaking changes wouldn't be in a separate library. But at the same time I'm not the maintainer and if they can make things easier for you, you might as well do it.

**Comment by kennyjwilli** [comment]
@Frozenlock fyi, this is the direction I'd like to take. It was merged and deployed in 0.2.0.

**Pull request merged**
